
## Dependencies

FROM node:21-alpine3.19 AS deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


## Builder - Construye la aplicación
FROM node:21-alpine3.19 AS build

WORKDIR /usr/src/app

# Copiar de deps los modulos node_modules
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar el código fuente de la aplicación
COPY . .

# Run npm run test
RUN npm run build

# Limpieza de modules de node que no necesito
RUN npm ci -f --only=production && npm cache clean --force

RUN npx prisma generate

## Crear la imagen final
FROM node:21-alpine3.19 AS production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta dist

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

# Cambiar al usuario node
USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]
